### PR TITLE
Alt text for clickable icons

### PR DESCRIPTION
**Pull request by aurorarhagen**
Added alternative, descriptive text to the hamburger menu button and the edit project name button in the sidebar for WCAG compliance.
#94

### CODE REVIEW

**Review by ykjellin — CHANGES_REQUESTED** [review]
I think it would be prudent to add alt text or aria labels respectively to other elements missing it on the page aswell. I am not sure if it was in the scope of the task you were provided this morning.

**Comment by aurorarhagen** [comment]
All errors that WAVE registered will be fixed, but they are separated into 3 different tasks and will have their own branches. So, I will also work on a branch for the aria menus and empty link error. All errors will be fixed, but in seperate branches and thereofre seperate pull requests, one for each "type" of error.

**Comment by ykjellin** [comment]
Ok all good. Will push this through then.

**Review by ykjellin — APPROVED** [review]
All good.

**Pull request merged**
