### PR TITLE
Sidebar structure + icons + light mode

### PR DESCRIPTION
**Pull request by Anne-Serine**
- Create side bar structure, right and left side (with buttons and some click events, ready to use)
- Added icons
- Made function to show icons in html (so that you easily can change color, and size e.g in dark mode / light mode)
- Implemented light mode

### CODE REVIEW

**Review by Alan-Brim — COMMENTED** [review]
`  <button
                class="sideBarBtn w-20 p-2 flex flex-col justify-center gap-3"
              >
                <span
                  data-icon="fitToWindow"
                  data-size="20"
                  data-class="text-ys-backgroundAndText dark:text-ys-textAndIconsLight"
                ></span>
                Fit to window
              </button>  `
Here you can use `text-start` to align the text with the icon on the right side.

**Review by Alan-Brim — COMMENTED** [review]
When the dark mode is on then I can see what I'm writing the code editor: 
The same is applied the cells

**Comment by Anne-Serine** [comment]
> When the dark mode is on then I can see what I'm writing the code editor: The same is applied the cells

Someone else is working on the syntax highlighting in code editor, so I haven´t done anything with that here.

**Comment by Anne-Serine** [comment]
> ` <button class="sideBarBtn w-20 p-2 flex flex-col justify-center gap-3" > <span data-icon="fitToWindow" data-size="20" data-class="text-ys-backgroundAndText dark:text-ys-textAndIconsLight" ></span> Fit to window </button> ` Here you can use `text-start` to align the text with the icon on the right side.

Thanks for the tip, but I have just followed the design from the design prototype 😄

**Review by Krihag — APPROVED** [review]

**Pull request merged**
