### PR TITLE
Add resizing of the cell sizes based on selected percentage in top menu

### LINKED ISSUE #122: Resize cell sizes based on selected percentage (in top menu)
- Create a function that resizes the cells in the sheet, based on the selected percentage selected from the top menu
- Create a event listener that calls the function when a user selects a percentage option

Make sure [this task](https://github.com/NoroffFEU/yeetsheet/issues/113) is done before starting

### PR DESCRIPTION
**Pull request by BergitTveit**

### CODE REVIEW

**Comment by FredrikMohag** [comment]
@BergitTveit The code looks really good but I'm having problem to get the checks completed (the header rules, page changed, redirect rules and netlify) I'm not really sure how to solve that! Maybe you know @Barvand ??

**Comment by Barvand** [comment]
I will have a look @FredrikMohag

**Comment by Barvand** [comment]
@FredrikMohag I have solved the issue. This was interfering with another feature that the other team made. I have merged the code together and all work has been preserved! @BergitTveit Good job!

**Comment by jonhenrikaavitsland** [comment]
@FredrikMohag @Barvand @BergitTveit Your merge has caused major conflicts. Either revert or fix please :)

**Pull request merged**
