### PR TITLE
Delete file option

### LINKED ISSUE #197: Delete existing file functionality
**User Story:**

As a user, I want the ability to delete an existing file from the application so that I can manage and organize my files efficiently by removing those I no longer need.

**Acceptance Criteria:**

- A "Delete File" option is available for each file.
- When the user selects this option, a confirmation prompt is displayed to prevent accidental deletion.
= Upon confirming, the selected file is permanently deleted and removed from the file list.
- The user is notified that the file has been successfully deleted.
- Deletion does not affect other files, and the file cannot be recovered after deletion.

### PR DESCRIPTION
**Pull request by Voidwaker**
- Implemented the delete changes button that clears all data in the spreadsheet.
- Added a two-step confirmation prompt to prevent accidental deletions.
- Updated IndexedDB logic to handle the deletion of cell data without affecting the structure.
- Added JsDocs

### CODE REVIEW

**Comment by FredrikMohag** [comment]
Good morning @Voidwaker, there is some conflicts in the code, can you see if you can solve it?

Conflicting files
index.html
src/js/main.js
src/js/spreadsheet/index.js

**Comment by FredrikMohag** [comment]
@Voidwaker  that solution did not work. Please undo your last work and I will have a look at the original merge-conflict

**Comment by Voidwaker** [comment]
should be resolved now @FredrikMohag could you take a look ?

**Comment by FredrikMohag** [comment]
Everything appears to be fixed and implemented as expected.

Good job @Voidwaker 👍

**Pull request merged**
