### PR TITLE
Feature/search

### LINKED ISSUE #82: Review and merge PR #31
Discuss this ticket with your team. Although it is a QA ticket, the QA engineer may still request some changes, so it is necessary to assign each PR to a developer. The developer will handle the requested changes.

PR #31

### PR DESCRIPTION
**Pull request by TaranJ**
Ads search function that searches for cell values in IndexedDB. For now the results are highlighted in red, but I can go back and change this once we know more about how the UI will look.

### CODE REVIEW

**Comment by Malkenes** [comment]
### Problems
**Accessibility issue**

Screen readers cannot perceive the search results when cells are highlighted based on the search input. This poses a significant accessibility barrier for users who rely on screen readers.

**UX issues**

Users cannot perceive search result matching cells that are outside the viewport, which affects the user experience

Users do not receive any hints or guidance on what they can search for. It’s unclear that they should search for cell values, which can lead to confusion and a poor user experience.

**Review by Alan-Brim — COMMENTED** [review]
To improve the readability and functionality of the search code, consider the following adjustments:

1. Enhance Readability: Ensure that the text within cells is easily readable by setting appropriate font size and wrapping text within cells.

2. Indicate Number of Results: Add an indicator showing the total number of results found after the search is completed.

**Comment by ttowntom** [comment]
@jonhavbra87 make sure input does not move when text is visible before merge

**Comment by ttowntom** [comment]
@ykjellin This PR is ready for review

**Review by ykjellin — CHANGES_REQUESTED** [review]
Merge conflict must be resolved before merge: [conflict](https://github.com/NoroffFEU/yeetsheet/pull/31/conflicts).

**Review by ykjellin — APPROVED** [review]
Conflict resolved. Looks good.

**Pull request merged**
