### PR TITLE
Import/export feature for CSV and JSON formats

### PR DESCRIPTION
**Pull request by maglus02**
- Adds functionality for importing CSV and JSON files through the file dropdown.
- Adds functionality for exporting in either CSV or JSON format.

### CODE REVIEW

**Comment by Malkenes** [comment]
[Design-guide](https://github.com/NoroffFEU/yeetsheet/discussions/36)
Style guide has an import flow you should include

**Comment by maglus02** [comment]
> [Design-guide](https://github.com/NoroffFEU/yeetsheet/discussions/36) Style guide has an import flow you should include

Thanks for the heads up!

**Review by Alan-Brim — COMMENTED** [review]
I have been able to import the data as csv and json files. But on importing I was just able to import the json files.  Othe than that very well done

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR Can you please resolve these conflicts

**Review by jonhenrikaavitsland — APPROVED** [review]
The changes look ok
Remove conflict markers and resolve.

**Review by sulenchy — CHANGES_REQUESTED** [review]
There is a conflict on this again

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR Please resolve the conflicts and ask for my review.

**Review by jonhenrikaavitsland — CHANGES_REQUESTED** [review]
@RamonaXR please fix the issues causing checks to fail.

**Review by jonhenrikaavitsland — APPROVED** [review]
@RamonaXR good work

**Pull request merged**
