### PR TITLE
Manage Columns and Rows in the Sheet 

### LINKED ISSUE #199: Manage Columns and Rows in the Sheet
**User Story:**

As a user, I want the ability to add or delete columns and rows within the sheet so that I can modify the structure of the sheet as needed for better organization and data management.

**Acceptance Criteria:**

- Users can add a new column to the sheet at any position.
- Users can delete an existing column from the sheet without affecting other columns.
- Users can add a new row to the sheet at any position.
- Users can delete an existing row from the sheet without affecting other rows.
- After adding or deleting columns or rows, the data remains intact and properly aligned.
- There are clear options (e.g., buttons or context menus) for adding and deleting columns/rows.

### PR DESCRIPTION
**Pull request by aurorarhagen**
Configurated the menu which opens on right-click on the rows and columns to better fit with the theme in light mode. Changed the direction of the arrow icons to correspond with the text.

### CODE REVIEW

**Comment by aurorarhagen** [comment]
@ykjellin ready for merge!

**Comment by aurorarhagen** [comment]
@ykjellin Ready for merge! We were unable to properly implement the feature to add rows below/above and delete them so there is a bug where the text in the cells are dupliacted when the user tries to add a new row above/beloe the current one. The same functions for the columns work as expected.

**Review by ykjellin — CHANGES_REQUESTED** [review]
Introduces new errors.

**Comment by ykjellin** [comment]
image

**Comment by ykjellin** [comment]
The function itself seems to be working as intended

**Comment by Kinenystuen** [comment]
@ykjellin To remove the errors occuring, you need to delete your existing database SpreadsheetDB in application when inspecting the site, then reload the page.

**Comment by Kinenystuen** [comment]
@ykjellin changes done, removed add row function, because of disfunction

**Review by ykjellin — APPROVED** [review]
Looks god. thank you

**Pull request merged**
